# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from UIPathAPI.configuration import Configuration


class PackageUploadedEvent(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'key': 'str',
        'name': 'str',
        'version': 'str',
        'feed_id': 'str',
        'type': 'str',
        'description': 'str',
        'folder_key': 'str',
        'tags': 'list[TagDto]',
        'event_time': 'datetime',
        'event_source': 'object'
    }

    attribute_map = {
        'key': 'key',
        'name': 'name',
        'version': 'version',
        'feed_id': 'feedId',
        'type': 'type',
        'description': 'description',
        'folder_key': 'folderKey',
        'tags': 'tags',
        'event_time': 'eventTime',
        'event_source': 'eventSource'
    }

    def __init__(self, key=None, name=None, version=None, feed_id=None, type=None, description=None, folder_key=None, tags=None, event_time=None, event_source=None, _configuration=None):  # noqa: E501
        """PackageUploadedEvent - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._key = None
        self._name = None
        self._version = None
        self._feed_id = None
        self._type = None
        self._description = None
        self._folder_key = None
        self._tags = None
        self._event_time = None
        self._event_source = None
        self.discriminator = None

        if key is not None:
            self.key = key
        if name is not None:
            self.name = name
        if version is not None:
            self.version = version
        if feed_id is not None:
            self.feed_id = feed_id
        if type is not None:
            self.type = type
        if description is not None:
            self.description = description
        if folder_key is not None:
            self.folder_key = folder_key
        if tags is not None:
            self.tags = tags
        if event_time is not None:
            self.event_time = event_time
        if event_source is not None:
            self.event_source = event_source

    @property
    def key(self):
        """Gets the key of this PackageUploadedEvent.  # noqa: E501


        :return: The key of this PackageUploadedEvent.  # noqa: E501
        :rtype: str
        """
        return self._key

    @key.setter
    def key(self, key):
        """Sets the key of this PackageUploadedEvent.


        :param key: The key of this PackageUploadedEvent.  # noqa: E501
        :type: str
        """

        self._key = key

    @property
    def name(self):
        """Gets the name of this PackageUploadedEvent.  # noqa: E501


        :return: The name of this PackageUploadedEvent.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PackageUploadedEvent.


        :param name: The name of this PackageUploadedEvent.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def version(self):
        """Gets the version of this PackageUploadedEvent.  # noqa: E501


        :return: The version of this PackageUploadedEvent.  # noqa: E501
        :rtype: str
        """
        return self._version

    @version.setter
    def version(self, version):
        """Sets the version of this PackageUploadedEvent.


        :param version: The version of this PackageUploadedEvent.  # noqa: E501
        :type: str
        """

        self._version = version

    @property
    def feed_id(self):
        """Gets the feed_id of this PackageUploadedEvent.  # noqa: E501


        :return: The feed_id of this PackageUploadedEvent.  # noqa: E501
        :rtype: str
        """
        return self._feed_id

    @feed_id.setter
    def feed_id(self, feed_id):
        """Sets the feed_id of this PackageUploadedEvent.


        :param feed_id: The feed_id of this PackageUploadedEvent.  # noqa: E501
        :type: str
        """

        self._feed_id = feed_id

    @property
    def type(self):
        """Gets the type of this PackageUploadedEvent.  # noqa: E501


        :return: The type of this PackageUploadedEvent.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this PackageUploadedEvent.


        :param type: The type of this PackageUploadedEvent.  # noqa: E501
        :type: str
        """
        allowed_values = ["Undefined", "Processes", "Libraries", "PersonalWorkspace", "FolderHierarchy"]  # noqa: E501
        if (self._configuration.client_side_validation and
                type not in allowed_values):
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def description(self):
        """Gets the description of this PackageUploadedEvent.  # noqa: E501


        :return: The description of this PackageUploadedEvent.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this PackageUploadedEvent.


        :param description: The description of this PackageUploadedEvent.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def folder_key(self):
        """Gets the folder_key of this PackageUploadedEvent.  # noqa: E501


        :return: The folder_key of this PackageUploadedEvent.  # noqa: E501
        :rtype: str
        """
        return self._folder_key

    @folder_key.setter
    def folder_key(self, folder_key):
        """Sets the folder_key of this PackageUploadedEvent.


        :param folder_key: The folder_key of this PackageUploadedEvent.  # noqa: E501
        :type: str
        """

        self._folder_key = folder_key

    @property
    def tags(self):
        """Gets the tags of this PackageUploadedEvent.  # noqa: E501


        :return: The tags of this PackageUploadedEvent.  # noqa: E501
        :rtype: list[TagDto]
        """
        return self._tags

    @tags.setter
    def tags(self, tags):
        """Sets the tags of this PackageUploadedEvent.


        :param tags: The tags of this PackageUploadedEvent.  # noqa: E501
        :type: list[TagDto]
        """

        self._tags = tags

    @property
    def event_time(self):
        """Gets the event_time of this PackageUploadedEvent.  # noqa: E501


        :return: The event_time of this PackageUploadedEvent.  # noqa: E501
        :rtype: datetime
        """
        return self._event_time

    @event_time.setter
    def event_time(self, event_time):
        """Sets the event_time of this PackageUploadedEvent.


        :param event_time: The event_time of this PackageUploadedEvent.  # noqa: E501
        :type: datetime
        """

        self._event_time = event_time

    @property
    def event_source(self):
        """Gets the event_source of this PackageUploadedEvent.  # noqa: E501


        :return: The event_source of this PackageUploadedEvent.  # noqa: E501
        :rtype: object
        """
        return self._event_source

    @event_source.setter
    def event_source(self, event_source):
        """Sets the event_source of this PackageUploadedEvent.


        :param event_source: The event_source of this PackageUploadedEvent.  # noqa: E501
        :type: object
        """

        self._event_source = event_source

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PackageUploadedEvent, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PackageUploadedEvent):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, PackageUploadedEvent):
            return True

        return self.to_dict() != other.to_dict()
