# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.assets_set_robot_assets_by_key_request import AssetsSetRobotAssetsByKeyRequest  # noqa: E501
from UIPathAPI.rest import ApiException


class TestAssetsSetRobotAssetsByKeyRequest(unittest.TestCase):
    """AssetsSetRobotAssetsByKeyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetsSetRobotAssetsByKeyRequest(self):
        """Test AssetsSetRobotAssetsByKeyRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.assets_set_robot_assets_by_key_request.AssetsSetRobotAssetsByKeyRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
