# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.entry_point_dto import EntryPointDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestEntryPointDto(unittest.TestCase):
    """EntryPointDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntryPointDto(self):
        """Test EntryPointDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.entry_point_dto.EntryPointDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
