# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_task_activity_dto import ODataValueOfIEnumerableOfTaskActivityDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfTaskActivityDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfTaskActivityDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfTaskActivityDto(self):
        """Test ODataValueOfIEnumerableOfTaskActivityDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_task_activity_dto.ODataValueOfIEnumerableOfTaskActivityDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
