# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_personal_workspace_dto import ODataValueOfIEnumerableOfPersonalWorkspaceDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfPersonalWorkspaceDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfPersonalWorkspaceDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfPersonalWorkspaceDto(self):
        """Test ODataValueOfIEnumerableOfPersonalWorkspaceDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_personal_workspace_dto.ODataValueOfIEnumerableOfPersonalWorkspaceDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
