# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.licenses_named_user_api import LicensesNamedUserApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestLicensesNamedUserApi(unittest.TestCase):
    """LicensesNamedUserApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.licenses_named_user_api.LicensesNamedUserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_licenses_named_user_get_licenses_named_user_by_robottype(self):
        """Test case for licenses_named_user_get_licenses_named_user_by_robottype

        Gets named-user licenses.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
