# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.release_dto import ReleaseDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestReleaseDto(unittest.TestCase):
    """ReleaseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReleaseDto(self):
        """Test ReleaseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.release_dto.ReleaseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
