# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_user_roles_dto import ODataValueOfIEnumerableOfUserRolesDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfUserRolesDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfUserRolesDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfUserRolesDto(self):
        """Test ODataValueOfIEnumerableOfUserRolesDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_user_roles_dto.ODataValueOfIEnumerableOfUserRolesDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
