# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.extended_calendar_dto import ExtendedCalendarDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestExtendedCalendarDto(unittest.TestCase):
    """ExtendedCalendarDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtendedCalendarDto(self):
        """Test ExtendedCalendarDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.extended_calendar_dto.ExtendedCalendarDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
