# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.simple_user_entity_dto import SimpleUserEntityDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestSimpleUserEntityDto(unittest.TestCase):
    """SimpleUserEntityDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimpleUserEntityDto(self):
        """Test SimpleUserEntityDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.simple_user_entity_dto.SimpleUserEntityDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
