# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_job_trigger_with_wait_events_dto import ODataValueOfIEnumerableOfJobTriggerWithWaitEventsDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfJobTriggerWithWaitEventsDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfJobTriggerWithWaitEventsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfJobTriggerWithWaitEventsDto(self):
        """Test ODataValueOfIEnumerableOfJobTriggerWithWaitEventsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_job_trigger_with_wait_events_dto.ODataValueOfIEnumerableOfJobTriggerWithWaitEventsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
