# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.tasks_assign_request import TasksAssignRequest  # noqa: E501
from UIPathAPI.rest import ApiException


class TestTasksAssignRequest(unittest.TestCase):
    """TasksAssignRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTasksAssignRequest(self):
        """Test TasksAssignRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.tasks_assign_request.TasksAssignRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
