# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.simple_machine_dto import SimpleMachineDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestSimpleMachineDto(unittest.TestCase):
    """SimpleMachineDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSimpleMachineDto(self):
        """Test SimpleMachineDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.simple_machine_dto.SimpleMachineDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
