# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.queue_item_simple_event_dto import QueueItemSimpleEventDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestQueueItemSimpleEventDto(unittest.TestCase):
    """QueueItemSimpleEventDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueueItemSimpleEventDto(self):
        """Test QueueItemSimpleEventDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.queue_item_simple_event_dto.QueueItemSimpleEventDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
