# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_release_dto import ODataValueOfIEnumerableOfReleaseDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfReleaseDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfReleaseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfReleaseDto(self):
        """Test ODataValueOfIEnumerableOfReleaseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_release_dto.ODataValueOfIEnumerableOfReleaseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
