# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.queue_items_abandoned_event_dto import QueueItemsAbandonedEventDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestQueueItemsAbandonedEventDto(unittest.TestCase):
    """QueueItemsAbandonedEventDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueueItemsAbandonedEventDto(self):
        """Test QueueItemsAbandonedEventDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.queue_items_abandoned_event_dto.QueueItemsAbandonedEventDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
