# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.language_info import LanguageInfo  # noqa: E501
from UIPathAPI.rest import ApiException


class TestLanguageInfo(unittest.TestCase):
    """LanguageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguageInfo(self):
        """Test LanguageInfo"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.language_info.LanguageInfo()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
