# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.licensing_api import LicensingApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestLicensingApi(unittest.TestCase):
    """LicensingApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.licensing_api.LicensingApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_licensing_acquire(self):
        """Test case for licensing_acquire

        Acquire license units  # noqa: E501
        """
        pass

    def test_licensing_release(self):
        """Test case for licensing_release

        Release acquired license units  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
