# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_bulk_item_dto_of_string import ODataValueOfIEnumerableOfBulkItemDtoOfString  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfBulkItemDtoOfString(unittest.TestCase):
    """ODataValueOfIEnumerableOfBulkItemDtoOfString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfBulkItemDtoOfString(self):
        """Test ODataValueOfIEnumerableOfBulkItemDtoOfString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_bulk_item_dto_of_string.ODataValueOfIEnumerableOfBulkItemDtoOfString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
