# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.user_login_info_dto import UserLoginInfoDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestUserLoginInfoDto(unittest.TestCase):
    """UserLoginInfoDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserLoginInfoDto(self):
        """Test UserLoginInfoDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.user_login_info_dto.UserLoginInfoDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
