# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_credentials_proxy_resource_dto import ODataValueOfIEnumerableOfCredentialsProxyResourceDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfCredentialsProxyResourceDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfCredentialsProxyResourceDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfCredentialsProxyResourceDto(self):
        """Test ODataValueOfIEnumerableOfCredentialsProxyResourceDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_credentials_proxy_resource_dto.ODataValueOfIEnumerableOfCredentialsProxyResourceDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
