# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.test_case_definitions_api import TestCaseDefinitionsApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestTestCaseDefinitionsApi(unittest.TestCase):
    """TestCaseDefinitionsApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.test_case_definitions_api.TestCaseDefinitionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_test_case_definitions_get(self):
        """Test case for test_case_definitions_get

        Returns a list of Test Case Definitions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
