# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_job_dto import ODataValueOfIEnumerableOfJobDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfJobDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfJobDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfJobDto(self):
        """Test ODataValueOfIEnumerableOfJobDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_job_dto.ODataValueOfIEnumerableOfJobDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
