# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.bulk_operation_response_dto_of_int64 import BulkOperationResponseDtoOfInt64  # noqa: E501
from UIPathAPI.rest import ApiException


class TestBulkOperationResponseDtoOfInt64(unittest.TestCase):
    """BulkOperationResponseDtoOfInt64 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBulkOperationResponseDtoOfInt64(self):
        """Test BulkOperationResponseDtoOfInt64"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.bulk_operation_response_dto_of_int64.BulkOperationResponseDtoOfInt64()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
