# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.export_model import ExportModel  # noqa: E501
from UIPathAPI.rest import ApiException


class TestExportModel(unittest.TestCase):
    """ExportModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExportModel(self):
        """Test ExportModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.export_model.ExportModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
