# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.test_data_queue_bulk_add_items_dto import TestDataQueueBulkAddItemsDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestTestDataQueueBulkAddItemsDto(unittest.TestCase):
    """TestDataQueueBulkAddItemsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTestDataQueueBulkAddItemsDto(self):
        """Test TestDataQueueBulkAddItemsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.test_data_queue_bulk_add_items_dto.TestDataQueueBulkAddItemsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
