# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_audit_log_dto import ODataValueOfIEnumerableOfAuditLogDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfAuditLogDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfAuditLogDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfAuditLogDto(self):
        """Test ODataValueOfIEnumerableOfAuditLogDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_audit_log_dto.ODataValueOfIEnumerableOfAuditLogDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
