# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.license_named_user_dto import LicenseNamedUserDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestLicenseNamedUserDto(unittest.TestCase):
    """LicenseNamedUserDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLicenseNamedUserDto(self):
        """Test LicenseNamedUserDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.license_named_user_dto.LicenseNamedUserDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
