# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_host_license_dto import ODataValueOfIEnumerableOfHostLicenseDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfHostLicenseDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfHostLicenseDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfHostLicenseDto(self):
        """Test ODataValueOfIEnumerableOfHostLicenseDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_host_license_dto.ODataValueOfIEnumerableOfHostLicenseDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
