# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.tenants_api import TenantsApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestTenantsApi(unittest.TestCase):
    """TenantsApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.tenants_api.TenantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_tenants_delete_by_id(self):
        """Test case for tenants_delete_by_id

        Deletes a tenant based on its id.  # noqa: E501
        """
        pass

    def test_tenants_get(self):
        """Test case for tenants_get

        Gets tenants.  # noqa: E501
        """
        pass

    def test_tenants_get_by_id(self):
        """Test case for tenants_get_by_id

        Gets a single tenant based on its id.  # noqa: E501
        """
        pass

    def test_tenants_patch_by_id(self):
        """Test case for tenants_patch_by_id

        Partially updates a tenant  # noqa: E501
        """
        pass

    def test_tenants_post(self):
        """Test case for tenants_post

        Creates a tenant.  # noqa: E501
        """
        pass

    def test_tenants_set_active(self):
        """Test case for tenants_set_active

        Toggles the active status of tenants  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
