# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.wrapped_environment_dto import WrappedEnvironmentDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestWrappedEnvironmentDto(unittest.TestCase):
    """WrappedEnvironmentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWrappedEnvironmentDto(self):
        """Test WrappedEnvironmentDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.wrapped_environment_dto.WrappedEnvironmentDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
