# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.robots_from_folder_model import RobotsFromFolderModel  # noqa: E501
from UIPathAPI.rest import ApiException


class TestRobotsFromFolderModel(unittest.TestCase):
    """RobotsFromFolderModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRobotsFromFolderModel(self):
        """Test RobotsFromFolderModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.robots_from_folder_model.RobotsFromFolderModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
