# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.task_definitions_api import TaskDefinitionsApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestTaskDefinitionsApi(unittest.TestCase):
    """TaskDefinitionsApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.task_definitions_api.TaskDefinitionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_task_definitions_create_task_definition(self):
        """Test case for task_definitions_create_task_definition

        Creates a new Task Definition.  # noqa: E501
        """
        pass

    def test_task_definitions_get(self):
        """Test case for task_definitions_get

        Gets Task Definition objects with the given OData queries.  # noqa: E501
        """
        pass

    def test_task_definitions_get_by_id(self):
        """Test case for task_definitions_get_by_id

        Gets a Task Definition item by Id.  # noqa: E501
        """
        pass

    def test_task_definitions_update_task_definition_by_id(self):
        """Test case for task_definitions_update_task_definition_by_id

        Updates Task Definition.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
