# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.jobs_created_event_dto import JobsCreatedEventDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestJobsCreatedEventDto(unittest.TestCase):
    """JobsCreatedEventDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobsCreatedEventDto(self):
        """Test JobsCreatedEventDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.jobs_created_event_dto.JobsCreatedEventDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
