# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_dictionary_of_int64_boolean import ODataValueOfIDictionaryOfInt64Boolean  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIDictionaryOfInt64Boolean(unittest.TestCase):
    """ODataValueOfIDictionaryOfInt64Boolean unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIDictionaryOfInt64Boolean(self):
        """Test ODataValueOfIDictionaryOfInt64Boolean"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_dictionary_of_int64_boolean.ODataValueOfIDictionaryOfInt64Boolean()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
