# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.role_users_dto import RoleUsersDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestRoleUsersDto(unittest.TestCase):
    """RoleUsersDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRoleUsersDto(self):
        """Test RoleUsersDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.role_users_dto.RoleUsersDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
