# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.extended_folder_dto import ExtendedFolderDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestExtendedFolderDto(unittest.TestCase):
    """ExtendedFolderDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testExtendedFolderDto(self):
        """Test ExtendedFolderDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.extended_folder_dto.ExtendedFolderDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
