# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_settings_dto import ODataValueOfIEnumerableOfSettingsDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfSettingsDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfSettingsDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfSettingsDto(self):
        """Test ODataValueOfIEnumerableOfSettingsDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_settings_dto.ODataValueOfIEnumerableOfSettingsDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
