# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.queue_item_failed_event_dto import QueueItemFailedEventDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestQueueItemFailedEventDto(unittest.TestCase):
    """QueueItemFailedEventDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testQueueItemFailedEventDto(self):
        """Test QueueItemFailedEventDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.queue_item_failed_event_dto.QueueItemFailedEventDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
