# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.asset_folders_share_dto import AssetFoldersShareDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestAssetFoldersShareDto(unittest.TestCase):
    """AssetFoldersShareDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAssetFoldersShareDto(self):
        """Test AssetFoldersShareDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.asset_folders_share_dto.AssetFoldersShareDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
