# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.alerts_mark_as_read_request import AlertsMarkAsReadRequest  # noqa: E501
from UIPathAPI.rest import ApiException


class TestAlertsMarkAsReadRequest(unittest.TestCase):
    """AlertsMarkAsReadRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlertsMarkAsReadRequest(self):
        """Test AlertsMarkAsReadRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.alerts_mark_as_read_request.AlertsMarkAsReadRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
