# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.bucket_folders_share_dto import BucketFoldersShareDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestBucketFoldersShareDto(unittest.TestCase):
    """BucketFoldersShareDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBucketFoldersShareDto(self):
        """Test BucketFoldersShareDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.bucket_folders_share_dto.BucketFoldersShareDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
