# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.user_login_attempt_dto import UserLoginAttemptDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestUserLoginAttemptDto(unittest.TestCase):
    """UserLoginAttemptDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserLoginAttemptDto(self):
        """Test UserLoginAttemptDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.user_login_attempt_dto.UserLoginAttemptDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
