# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_log_dto import ODataValueOfIEnumerableOfLogDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfLogDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfLogDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfLogDto(self):
        """Test ODataValueOfIEnumerableOfLogDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_log_dto.ODataValueOfIEnumerableOfLogDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
