# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.directory_object_dto import DirectoryObjectDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestDirectoryObjectDto(unittest.TestCase):
    """DirectoryObjectDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDirectoryObjectDto(self):
        """Test DirectoryObjectDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.directory_object_dto.DirectoryObjectDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
