# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_queue_item_dto import ODataValueOfIEnumerableOfQueueItemDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfQueueItemDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfQueueItemDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfQueueItemDto(self):
        """Test ODataValueOfIEnumerableOfQueueItemDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_queue_item_dto.ODataValueOfIEnumerableOfQueueItemDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
