# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.audit_logs_api import AuditLogsApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestAuditLogsApi(unittest.TestCase):
    """AuditLogsApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.audit_logs_api.AuditLogsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_audit_logs_export(self):
        """Test case for audit_logs_export

        Requests a CSV export of filtered items.  # noqa: E501
        """
        pass

    def test_audit_logs_get(self):
        """Test case for audit_logs_get

        Gets Audit logs.  # noqa: E501
        """
        pass

    def test_audit_logs_get_audit_log_details_by_auditlogid(self):
        """Test case for audit_logs_get_audit_log_details_by_auditlogid

        Returns audit log details by audit log id  # noqa: E501
        """
        pass

    def test_audit_logs_reports(self):
        """Test case for audit_logs_reports

        Returns a CSV containing the filtered audit.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
