# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.domain_user_assignment_dto import DomainUserAssignmentDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestDomainUserAssignmentDto(unittest.TestCase):
    """DomainUserAssignmentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDomainUserAssignmentDto(self):
        """Test DomainUserAssignmentDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.domain_user_assignment_dto.DomainUserAssignmentDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
