# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.webhook_task_assignment_changed_dto import WebhookTaskAssignmentChangedDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestWebhookTaskAssignmentChangedDto(unittest.TestCase):
    """WebhookTaskAssignmentChangedDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebhookTaskAssignmentChangedDto(self):
        """Test WebhookTaskAssignmentChangedDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.webhook_task_assignment_changed_dto.WebhookTaskAssignmentChangedDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
