# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.job_dto import JobDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestJobDto(unittest.TestCase):
    """JobDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobDto(self):
        """Test JobDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.job_dto.JobDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
