# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.permissions_api import PermissionsApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestPermissionsApi(unittest.TestCase):
    """PermissionsApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.permissions_api.PermissionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_permissions_get(self):
        """Test case for permissions_get

        Gets permissions.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
