# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.queue_retention_api import QueueRetentionApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestQueueRetentionApi(unittest.TestCase):
    """QueueRetentionApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.queue_retention_api.QueueRetentionApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_queue_retention_delete_by_id(self):
        """Test case for queue_retention_delete_by_id

        """
        pass

    def test_queue_retention_get(self):
        """Test case for queue_retention_get

        """
        pass

    def test_queue_retention_get_by_id(self):
        """Test case for queue_retention_get_by_id

        """
        pass

    def test_queue_retention_put_by_id(self):
        """Test case for queue_retention_put_by_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
