# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.queue_item_events_api import QueueItemEventsApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestQueueItemEventsApi(unittest.TestCase):
    """QueueItemEventsApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.queue_item_events_api.QueueItemEventsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_queue_item_events_get(self):
        """Test case for queue_item_events_get

        Gets the QueueItemEvents.  # noqa: E501
        """
        pass

    def test_queue_item_events_get_by_id(self):
        """Test case for queue_item_events_get_by_id

        Gets a QueueItemEvent by Id.  # noqa: E501
        """
        pass

    def test_queue_item_events_get_queue_item_events_history_by_queueitemid(self):
        """Test case for queue_item_events_get_queue_item_events_history_by_queueitemid

        Returns a collection of Queue Item Events associated to a Queue Item and all its related Queue Items.  A Queue Item is related to another if it was created as a retry of a failed Queue Item. They also share the same Key.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
