# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.key_value_pair_of_string_string import KeyValuePairOfStringString  # noqa: E501
from UIPathAPI.rest import ApiException


class TestKeyValuePairOfStringString(unittest.TestCase):
    """KeyValuePairOfStringString unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testKeyValuePairOfStringString(self):
        """Test KeyValuePairOfStringString"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.key_value_pair_of_string_string.KeyValuePairOfStringString()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
