# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_queue_item_comment_dto import ODataValueOfIEnumerableOfQueueItemCommentDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfQueueItemCommentDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfQueueItemCommentDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfQueueItemCommentDto(self):
        """Test ODataValueOfIEnumerableOfQueueItemCommentDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_queue_item_comment_dto.ODataValueOfIEnumerableOfQueueItemCommentDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
