# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.job_suspended_event_dto import JobSuspendedEventDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestJobSuspendedEventDto(unittest.TestCase):
    """JobSuspendedEventDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testJobSuspendedEventDto(self):
        """Test JobSuspendedEventDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.job_suspended_event_dto.JobSuspendedEventDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
