# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.update_machines_to_folder_associations_request import UpdateMachinesToFolderAssociationsRequest  # noqa: E501
from UIPathAPI.rest import ApiException


class TestUpdateMachinesToFolderAssociationsRequest(unittest.TestCase):
    """UpdateMachinesToFolderAssociationsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateMachinesToFolderAssociationsRequest(self):
        """Test UpdateMachinesToFolderAssociationsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.update_machines_to_folder_associations_request.UpdateMachinesToFolderAssociationsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
