# coding: utf-8

"""
    UiPath.WebApi 17.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 17.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.machine_robot_session_dto import MachineRobotSessionDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestMachineRobotSessionDto(unittest.TestCase):
    """MachineRobotSessionDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMachineRobotSessionDto(self):
        """Test MachineRobotSessionDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.machine_robot_session_dto.MachineRobotSessionDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
