# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.models.o_data_value_of_i_enumerable_of_machine_folder_dto import ODataValueOfIEnumerableOfMachineFolderDto  # noqa: E501
from UIPathAPI.rest import ApiException


class TestODataValueOfIEnumerableOfMachineFolderDto(unittest.TestCase):
    """ODataValueOfIEnumerableOfMachineFolderDto unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testODataValueOfIEnumerableOfMachineFolderDto(self):
        """Test ODataValueOfIEnumerableOfMachineFolderDto"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UIPathAPI.models.o_data_value_of_i_enumerable_of_machine_folder_dto.ODataValueOfIEnumerableOfMachineFolderDto()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
