# coding: utf-8

"""
    UiPath.WebApi 16.0

    Orchestrator API  # noqa: E501

    OpenAPI spec version: 16.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import UIPathAPI
from UIPathAPI.api.status_api import StatusApi  # noqa: E501
from UIPathAPI.rest import ApiException


class TestStatusApi(unittest.TestCase):
    """StatusApi unit test stubs"""

    def setUp(self):
        self.api = UIPathAPI.api.status_api.StatusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_status_get(self):
        """Test case for status_get

        Returns whether the current endpoint should be serving traffic  # noqa: E501
        """
        pass

    def test_status_verify_host_availibility(self):
        """Test case for status_verify_host_availibility

        """
        pass


if __name__ == '__main__':
    unittest.main()
