from __future__ import absolute_import

# flake8: noqa

# import apis into api package
from UIPathAPI.api.oauth2_api import OAuth2Api
from UIPathAPI.api.account_api import AccountApi
from UIPathAPI.api.alerts_api import AlertsApi
from UIPathAPI.api.assets_api import AssetsApi
from UIPathAPI.api.audit_logs_api import AuditLogsApi
from UIPathAPI.api.buckets_api import BucketsApi
from UIPathAPI.api.calendars_api import CalendarsApi
from UIPathAPI.api.credential_stores_api import CredentialStoresApi
from UIPathAPI.api.directory_service_api import DirectoryServiceApi
from UIPathAPI.api.environments_api import EnvironmentsApi
from UIPathAPI.api.execution_media_api import ExecutionMediaApi
from UIPathAPI.api.exports_api import ExportsApi
from UIPathAPI.api.folders_api import FoldersApi
from UIPathAPI.api.folders_navigation_api import FoldersNavigationApi
from UIPathAPI.api.generic_tasks_api import GenericTasksApi
from UIPathAPI.api.host_licenses_api import HostLicensesApi
from UIPathAPI.api.job_triggers_api import JobTriggersApi
from UIPathAPI.api.jobs_api import JobsApi
from UIPathAPI.api.libraries_api import LibrariesApi
from UIPathAPI.api.licenses_named_user_api import LicensesNamedUserApi
from UIPathAPI.api.licenses_runtime_api import LicensesRuntimeApi
from UIPathAPI.api.licensing_api import LicensingApi
from UIPathAPI.api.logs_api import LogsApi
from UIPathAPI.api.machines_api import MachinesApi
from UIPathAPI.api.maintenance_api import MaintenanceApi
from UIPathAPI.api.organization_units_api import OrganizationUnitsApi
from UIPathAPI.api.package_feeds_api import PackageFeedsApi
from UIPathAPI.api.permissions_api import PermissionsApi
from UIPathAPI.api.personal_workspaces_api import PersonalWorkspacesApi
from UIPathAPI.api.process_schedules_api import ProcessSchedulesApi
from UIPathAPI.api.processes_api import ProcessesApi
from UIPathAPI.api.queue_definitions_api import QueueDefinitionsApi
from UIPathAPI.api.queue_item_comments_api import QueueItemCommentsApi
from UIPathAPI.api.queue_item_events_api import QueueItemEventsApi
from UIPathAPI.api.queue_items_api import QueueItemsApi
from UIPathAPI.api.queue_processing_records_api import QueueProcessingRecordsApi
from UIPathAPI.api.queue_retention_api import QueueRetentionApi
from UIPathAPI.api.queues_api import QueuesApi
from UIPathAPI.api.release_retention_api import ReleaseRetentionApi
from UIPathAPI.api.releases_api import ReleasesApi
from UIPathAPI.api.robot_logs_api import RobotLogsApi
from UIPathAPI.api.robots_api import RobotsApi
from UIPathAPI.api.roles_api import RolesApi
from UIPathAPI.api.sessions_api import SessionsApi
from UIPathAPI.api.settings_api import SettingsApi
from UIPathAPI.api.stats_api import StatsApi
from UIPathAPI.api.status_api import StatusApi
from UIPathAPI.api.task_activities_api import TaskActivitiesApi
from UIPathAPI.api.task_catalogs_api import TaskCatalogsApi
from UIPathAPI.api.task_forms_api import TaskFormsApi
from UIPathAPI.api.task_notes_api import TaskNotesApi
from UIPathAPI.api.tasks_api import TasksApi
from UIPathAPI.api.tenants_api import TenantsApi
from UIPathAPI.api.test_automation_api import TestAutomationApi
from UIPathAPI.api.test_case_definitions_api import TestCaseDefinitionsApi
from UIPathAPI.api.test_case_executions_api import TestCaseExecutionsApi
from UIPathAPI.api.test_data_queue_actions_api import TestDataQueueActionsApi
from UIPathAPI.api.test_data_queue_items_api import TestDataQueueItemsApi
from UIPathAPI.api.test_data_queues_api import TestDataQueuesApi
from UIPathAPI.api.test_set_executions_api import TestSetExecutionsApi
from UIPathAPI.api.test_set_schedules_api import TestSetSchedulesApi
from UIPathAPI.api.test_sets_api import TestSetsApi
from UIPathAPI.api.translations_api import TranslationsApi
from UIPathAPI.api.user_login_attempts_api import UserLoginAttemptsApi
from UIPathAPI.api.users_api import UsersApi
from UIPathAPI.api.webhooks_api import WebhooksApi
